### ISSUE TITLE
What does it mean to be a standalone extension?

### ISSUE THREAD

**Issue by kyle-winkelman** [wiremock/gradle-wiremock-extension-plugins#11]
### Proposal

Should a standalone extension be:
- compatible with wiremock-standalone
- used alongside wiremock-standalone or separately
- be intended for use with test containers (similar to above question because the default image will include wiremock-standalone and therefore will need to be compatible)
- would the standalone extension ever be used with normal wiremock

The reason I am asking is because depending on what is envisioned I would expect the shadowjar to be created differently.

If it is to be compatible with wiremock-standalone, it should `relocate` the same packages as wiremock-standalone does.

If it is to be used alongside wiremock-standalone, it should define the wiremock dependencies as `shadow` to make the jar a lot smaller.

### Reproduction steps

Create a standalone extension that uses a transitive dependency of WireMock like `org.fasterxml.jackson` then put wiremock-standalone on the classpath before your extension. For example, using `Json.read(json, TypeReference<List<Example>> {} ())` will cause an issue because TypeReference in WireMock will be relocated to `wiremock.org.fasterxml.jackson` but your standalone extension will still be using `org.fasterxml.jackson`.

### References

[wiremock-standalone relocates to copy](https://github.com/wiremock/wiremock/blob/3.3.1/build.gradle#L291-L318)
[make standalone extension jar smaller by declaring these shadow](https://github.com/wiremock/gradle-wiremock-extension-plugins/blob/0.1.2/src/main/groovy/org.wiremock.tools.gradle.wiremock-extension-convention.gradle#L207-L210)

**Comment by oleg-nenashev** [comment]
It's a good question for @tomakehurst. Personally I would expect that indeed the standalone shaded jar properly handles relocation of upstream dependencies ootb

**Comment by tomakehurst** [comment]
I wouldn't recommend classifying an extension as standalone or otherwise, but instead having it build two JARs - one for use with WireMock core standalone, one with the standard build.

The gRPC is a good example of this (although it's not yet been upgraded to use Oleg's Gradle plugin, which simplifies the process of building in this way).
